### PR TITLE
Profile Added : Shariq2003 | Issue #750

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added my profile in the website as per the rules.
Completed #750 

@HimangshuSharma01 sir, please review and merge this

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@HimangshuSharma01 can you help fixing the conflicts

**Comment by Shariq2003** [comment]
> @HimangshuSharma01 can you help fixing the conflicts

just give me 1 mint

**Comment by Shariq2003** [comment]
> @HimangshuSharma01 can you help fixing the conflicts

@sanjay-kv please review now.

**Review by HimangshuSharma01 — APPROVED** [review]

**Comment by Shariq2003** [comment]
> > > @HimangshuSharma01 can you help fixing the conflicts
> > 
> > 
> > just give me 1 mint
> 
> Sir its now fixed

Yes, @sanjay-kv sir, you can merge now

**Comment by Shariq2003** [comment]
@HimangshuSharma01 @sanjay-kv sir, please add gssoc labels to my PR

**Pull request merged**
