### PR TITLE
New feature - Issue-936 : Changed the UI of Navbar, added features like filtering the profiles by Role ( Developers / Designer / Data Scientists ) and added sorting the profiles by followers count

### PR DESCRIPTION
**Pull request by sidgureja7803**
Changes:

a - UI Enhancements to Navbar:
Redesigned the Navbar for a more user-friendly and visually appealing experience.
Improved layout and responsiveness for better navigation across devices.

b - Profile Filtering by Role:
Added functionality to filter profiles based on roles, including:
1- Developers
2- Designers
3- Data Scientists
4 - Profile Sorting:

c - Implemented sorting options to sort profiles by:
Followers count (ascending/descending)
Impact: These updates enhance the user experience by making it easier to navigate through profiles based on specific criteria, improving overall usability.

NOTE - Access to the followers count via the API call, is forbidden from your end.
Please change it
i have added proper switch cases, for likes / views / followers
it will work, once data is allowed from your end.

### CODE REVIEW

**Comment by sidgureja7803** [comment]
why i am facing conflict issues ??
@HimangshuSharma01 and @sanjay-kv , where is it mentioned to merge the changes with the gh-pages branch.
I have worked, on 4-5 repos in the month of October and this is the first time i am facing this issue, for hacktober fest.
I just followed these steps, that were written in the Contributor MD file

git checkout gh-pages
git checkout -b  my-branch
git add .
git commit -m "Message"
git push origin my-branch

**Comment by sanjay-kv** [comment]
I think the PR changed lot of files, i hope you updating the correct branch `gh-pages`

**Comment by sidgureja7803** [comment]
> I think the PR changed lot of files, i hope you updating the correct branch `gh-pages`

@sanjay-kv , sir if you could tell me, how to update the correct branch ??
because, in the  beginning only, I switched the branch to gh-pages, and then i started working on my branch.
It is not mentioned anywhere, not even in the Contributing md file to....merge the changes to gh-pages branch.

**Comment by sanjay-kv** [comment]
@hey @sidgureja7803 you are changing on different branch so many file changes. this shouldnt be happening.

**Comment by sidgureja7803** [comment]
> @Hey @sidgureja7803 you are changing on different branch so many file changes. this shouldnt be happening.

@sanjay-kv , why i am facing this issue ??
@HimangshuSharma01 
Please help, whether i have to create a new branch or i have to commit the changes in the gh-pages branch ??

**Comment by sanjay-kv** [comment]
yes gh-pages branch

**Pull request closed without merging**
