### PR TITLE
Fixed/overlay

### PR DESCRIPTION
**Pull request by samar12-rad**
image
Now no of the elements are clickable when the overlay is opened, like navbar, links on the side like, youtube, linkedin, twitter, github, etc. 
The overlay now also encompasses the whole screen which was not the case earlier.
for issue #778

### CODE REVIEW

**Comment by sanjay-kv** [comment]
this has made changed to 1200 files @HimangshuSharma01 can you check this ?

**Comment by HimangshuSharma01** [comment]
> this has made changed to 1200 files @HimangshuSharma01 can you check this ?

okay sir

**Comment by HimangshuSharma01** [comment]
> this has made changed to 1200 files @HimangshuSharma01 can you check this ?

Sir it has wrong implementation there are same files repeating several times 
image
Screenshot 2024-10-20 213021

**Comment by sanjay-kv** [comment]
yes , then i will close the PR, it seems something went wrong while raising PR

**Pull request closed without merging**
