### PR TITLE
Feedback and rating page with navbar and footer 

### PR DESCRIPTION
**Pull request by shriyadindi**
I've added a new page for the feedback and rating of the user experience with navbar and footer for navigation.
issue no. #1203 

https://github.com/user-attachments/assets/9042c43d-89b1-47e6-97bd-614d6367468d

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
can you remove the change , and delete the feedback page,

**Comment by sanjay-kv** [comment]
@HimangshuSharma01

**Comment by sanjay-kv** [comment]
Someone changed the entire UI, we need to put it back how it was before. the UI look so ugly now

**Comment by shriyadindi** [comment]
@sanjay-kv Okay, you've assigned a level 2 label for the issue.

**Comment by shriyadindi** [comment]
@sanjay-kv Okay, I'll delete it and update, is it not looking nice? Should I make it again?

**Comment by sanjay-kv** [comment]
Naah. I want to revert all changes . You can get points. I didn't read the issue or PR properly and merged it

**Comment by shriyadindi** [comment]
@sanjay-kv I didnt make any changes in the exisitng ui, and you've given a level 2 label for the issue, and now you've given a level 1 label for the PR.

**Pull request merged**
