### PR TITLE
Added profile modal popup

### PR DESCRIPTION
**Pull request by MuKulsoop**
This is the second pull request created with the same functionality of the popup modal.

https://github.com/user-attachments/assets/f97c1eac-ef53-4b77-83f9-0820f772919d

### CODE REVIEW

**Comment by MuKulsoop** [comment]
Issue #664

**Comment by MuKulsoop** [comment]
@sanjay-kv Can you please review this PR.

**Review by sanjay-kv — APPROVED** [review]
awesome

**Comment by MuKulsoop** [comment]
Thank you very much

**Pull request merged**
