### PR TITLE
Twitter logo updated to X , hover effect adjusted  for X, also adjusted X for dark mode

### PR DESCRIPTION
**Pull request by Raj-Aditya-27**
Hi @sanjay-kv 

I fix the issue.
Issue no: #596

Issue:
As we update ourself , so should this application.
Updated Twitter logo to X and adjusted hover effect according to X theme and also adjusted it for dark theme

Before:
image
image

After:
image
image

### CODE REVIEW

**Comment by Raj-Aditya-27** [comment]
hi @sanjay-kv 
I'm facing to issue while forking as whole branches are forked instead of only gh-pages.
That's why this merge conflict occurs.
Can you help me to resolve this issue?

**Comment by sanjay-kv** [comment]
i will be clossing this issue, you have made changes to 75 files and there is lot of conflicts. 
kinda impossible to review manually. 

i hope you working on branch gh-pages

**Comment by Raj-Aditya-27** [comment]
Hii @sanjay-kv 

I'm requesting you to please open this issue.
I will do my best to resolve all of this conflict.
This is a platform to learn new things.
I want to take this challenge.
Please give me one chance.

**Comment by Raj-Aditya-27** [comment]
Hi @sanjay-kv 

Please open this issue as this issue is still in website.
I will do it shortly as i understand to solve merge conflicts.
give me a chance.

**Pull request closed without merging**
