### PR TITLE
Feature: Added Reveal elements on scroll

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#213 

### Preview of Feature

https://github.com/user-attachments/assets/3ca2bd25-6994-4993-a1fd-9c936c4e4c01

https://github.com/user-attachments/assets/d6a1e071-bcdd-402f-9509-2d147db8716f

https://github.com/user-attachments/assets/c3a6c6df-980b-4452-bc2a-8f8286d8459d

https://github.com/user-attachments/assets/44818b3f-bbbd-4567-8751-afae91a44f02

https://github.com/user-attachments/assets/3fd34f6e-d9cb-4bc3-a82c-124dbf3c0314

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sanjay-kv please review the PR.

**Comment by sanjay-kv** [comment]
we havent agreed to add to all page, only main page will do.

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
only main page if fine, remaining not required.

**Comment by Anjaliavv51** [comment]
> only main page if fine, remaining not required.

okay sir

**Comment by Anjaliavv51** [comment]
> only main page if fine, remaining not required.

sir i had removed script for remainig except for main page.

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir

**Review by Anjaliavv51 — COMMENTED** [review]
@sanjay-kv please review the PR.

**Comment by sanjay-kv** [comment]
there is lot of conflicts 
image

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir it is not allowing me to resolve the conflitcs.

image

**Comment by sanjay-kv** [comment]
the thing is you do pull before every push

**Comment by sanjay-kv** [comment]
the conflict is on lot of code base. doing manual is impossible.

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir okay

**Pull request closed without merging**
