### PR TITLE
[feat] Create MIT License

### PR DESCRIPTION
**Pull request by yehiarasheed**
### Description

This PR closes issue #914 concerning the creation of the MIT license for the project under the `gh-pages` branch, keeping a safe and sound environment for the Project owners and Contributors alike. The license was created on the year **2024** under the name **Recode Hive**.

### Screenshots

image

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by yehiarasheed** [comment]
@sanjay-kv, wasn't this a level2 issue?

**Comment by sanjay-kv** [comment]
in issue we never usually know what kind of implemetation unless you provide sample, by looking at the PR i think its quite basic so level1. else the other contributors will mark ur pr spam. hope u understand.

**Comment by yehiarasheed** [comment]
I understand, thing is you're a really experienced open-source contributor and you know that this is the way to implement a license, there's no harder method to implement it that I didn't do. So, I hope you give issues their deserved levels so that contributors are not surprised when they get a lower level on the PR than the one that they saw and expected on the issue. Plus it's not really spammy to give it a level2, adding a license protects all their work, and mine.

**Comment by sanjay-kv** [comment]
my bad, i got confused with coc file.

**Pull request merged**
