### PR TITLE
All contributors/add ujjwalshriv3

### PR DESCRIPTION
**Pull request by ujjwalshriv3**
plz  add @ujjwalshriv3 as a contributor for review #426
 @sanjay-kv sir plz add my profile
screencapture-github-ujjwalshriv3-2024-08-20-11_25_06

### CODE REVIEW

**Review by dinxsh — APPROVED** [review]
lgtm

**Comment by ujjwalshriv3** [comment]
> lgtm

plz merge my PR in all contributors #440 @dinxsh

**Comment by sanjay-kv** [comment]
you followed a wrong process. PR will be automatically raising by the bot when you create issue. i recommend to do it again,

**Comment by ujjwalshriv3** [comment]
> you followed a wrong process. PR will be automatically raising by the bot when you create issue. i recommend to do it again,

Ok sir

**Pull request closed without merging**
