### PR TITLE
add enhance/button-style-improve branch

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
This is output of my changes..

Screenshot 2024-10-21 154309
Screenshot 2024-10-21 154254

### CODE REVIEW

**Review by PriyanshuValiya — COMMENTED** [review]
Final Output Code

**Review by sanjay-kv — APPROVED** [review]
This is good change

**Comment by sanjay-kv** [comment]
Love the design

**Comment by PriyanshuValiya** [comment]
@sanjay-kv Hey, why points of this PR hasn't added in my GSSoC point table ?

**Pull request merged**
