### PR TITLE
Github links added on compare page

### PR DESCRIPTION
**Pull request by 17arindam**
-now github links are also fetched from api
-this links are clickable are user can visit their account
Screenshot 2024-10-09 034503

https://github.com/user-attachments/assets/b400440d-81b2-4ced-ae4c-5da9d68bcc17

### CODE REVIEW

**Comment by 17arindam** [comment]
@sanjay-kv please review my pr

**Review by sanjay-kv — APPROVED** [review]
awesome , can we add more features to compare here. @17arindam

**Comment by 17arindam** [comment]
@sanjay-kv yeah i am also searching for what else should be displayed on compare

**Comment by 17arindam** [comment]
@sanjay-kv please assign me level on this pr

**Comment by sanjay-kv** [comment]
sorry @17arindam i forgot to add fixed it now.

**Pull request merged**
