### PR TITLE
Compare page logo fix || ISSUE #1032 (RESOLVED CONFLICTS)

### PR DESCRIPTION
**Pull request by Jayesh-Waghmare**
I have added the logo to the compare page. 

image

@sanjay-kv @HimangshuSharma01 Sir, Please merge my PR under hacktoberfest, gssoc-ext labels.
This PR closes the issue #1032

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
there is conflcits.

**Comment by Jayesh-Waghmare** [comment]
@sanjay-kv @HimangshuSharma01  sir, then what I need to do?

**Comment by Jayesh-Waghmare** [comment]
Hi @sanjay-kv @HimangshuSharma01 sir, I have resolved the changes. Please accept and approve my PR

**Comment by Jayesh-Waghmare** [comment]
# # # Resolved Conflicts

I have resolved the issues in the branch. Please accept my PR under gssoc-ext and hacktoberfest labels

image


@sanjay-kv @HimangshuSharma01

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
