### PR TITLE
Create Deployment link

### PR DESCRIPTION
**Pull request by Meetpidev**
https://meetpidev.github.io/awesome-github-profiles/

issue #1259

Screenshot 2024-11-10 115610

### CODE REVIEW

**Comment by Meetpidev** [comment]
@sanjay-kv Please Review PR..

**Comment by sanjay-kv** [comment]
can i know what exactly change you made, did you redeploy it. 

i cant merge as the URL is different.

**Comment by Meetpidev** [comment]
@sanjay-kv i deployed it through the github.. check the URL

**Comment by Meetpidev** [comment]
@sanjay-kv and one more thing is that is gssoc leader board the points of PR that merged on 10/11 before 7 p.m. is not showing.. can you please tell me the reason behind it...  on 10/11 befor 7 p.m. lots of PR merged of mine  .. and its points isn't showing.. so thats why im asking..

**Comment by sanjay-kv** [comment]
https://github.com/orgs/GSSoC24/discussions/categories/leaderboard

u can raise issue here with screenshot and respective PR link,

**Comment by Meetpidev** [comment]
@sanjay-kv They said they can not help me.. as leaderboard not update now.. i humblely request you to tell GSSoC team.. there are many PRs that is not reflected.. all that PRs was accepted on 10 nov before 7 pm... even i can give all that PRs list.. .. please help me as my efforts will not be lost..

**Comment by sanjay-kv** [comment]
HI @Meetpidev 

atm we cant do any, 

we have already rolled newsletter, email, discord alerts on the 8th NOv regarding this. 
So people get opportunity to add all the unmerged PR made by PA. 

after leaderboard close if we make any change . it may help you but it will affect all other people on leaderboard ranking. 

We launched the mails and alerts for this reason. 

@MastanSayyad has already conveyed to you

**Pull request closed without merging**
