### PR TITLE
Update .all-contributorsrc

### PR DESCRIPTION
**Pull request by shubhagarwal1**
**This pull request enhances our contributor profile management by following these steps:**

**Identified New Contributors**: Retrieved all open issues titled "ADD Profile" to gather new contributor data.
**Data Formatting**: Converted the new contributor data to match the existing JSON structure.
**Removed Duplicates**: Compared the new data against the current all-contributors file to eliminate any duplicate entries.
**Merged Profiles**: Combined the cleaned contributor data with existing profiles, appending new contributors to the end to maintain order.

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
This is great update.

**Review by MastanSayyad — COMMENTED** [review]
Add `level1` @sanjay-kv 

code is formatted and the other existing key-value pair data is added

image

**Comment by shubhagarwal1** [comment]
> Add `level2` @sanjay-kv
> 
> code is formatted and the other existing key-value pair data is added
> 
> image

**Comment by shubhagarwal1** [comment]
> Add `level2` @sanjay-kv
> 
> code is formatted and the other existing key-value pair data is added
> 
> image

Hey @MastanSayyad lot of scrapping effort was also involved, to collect this data, please read the PR desc also.

**Comment by sanjay-kv** [comment]
@MastanSayyad 

i personally think there been lot of work involved, some of the work doesn't reflect by just looking at the code changes. 
and the impact to the repo was high because our bot stopped working. so this timely intervention made sure customer retention. so I don't think level down is necessary for this @shubhagarwal1

**Comment by MastanSayyad** [comment]
I get it, my bad.

**Pull request merged**
