### PR TITLE
Add Scroll-to-Top Button with Hover Effects and Dark Mode Support

### LINKED ISSUE #85: Can we add this simillar scroll to bottom
image

adapted idea from the gssoc website.

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @sanjay-kv 

- Issue closes #85

I have added the `Scroll To Top` button 

### Files Updated:
1. `styles.css`
2. `Index.html`
3. `ScrollToTop.js`
4. `GithubBadges.html`
5. `events.html`

- The button becomes visible when the user `scrolls` down more than `300 pixels`.
-  Added a smooth `transform` effect to the button and arrow on hover. The button slightly moves up, and the arrow moves up slightly as well.
- The button and arrow colors adjust based on the dark mode theme.
      1. Light Mode: Base Color is `#000000` Arrow `#ffffff` | On hover `#3e3e3e`
      2. Dark Mode: Base Color is `#ffffff` Arrow `#000000` | On hover `#b6b6b6ff`
- Updated button styling to include smooth transitions for color, opacity, and transform effects.

### Light Mode
image

### Dark Mode
image

### Transitions and Animations

https://github.com/user-attachments/assets/be309c50-9cfd-4644-8f9a-53304db41ceb

### Overall Screen Record

https://github.com/user-attachments/assets/1f320bbb-43fc-4540-88c1-82cba15d1f6b

The button works smoothly without lagging and ensuring the UI/Ux of the website
Please take a look and review it!

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @sanjay-kv I have added the Scroll to top button, Please take a look and review it!

**Comment by sanjay-kv** [comment]
there are some conflicts in the file , could you look into it @MastanSayyad

**Comment by MastanSayyad** [comment]
@sanjay-kv Resolved

**Review by sanjay-kv — COMMENTED** [review]
good

**Pull request merged**
