### PR TITLE
Added Help Page 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have added the Help Page template for the website 

https://github.com/user-attachments/assets/947651ff-40ba-4ccf-86b1-5e87cb27394c

closes : #168

### CODE REVIEW

**Comment by sanjay-kv** [comment]
can you push the other 2 PR to gh-branch as well. 

the blog page and github branch update is not yet reflected.

**Comment by Ayushmaanagarwal1211** [comment]
yes sir i am pushing

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir i have a little bit confusion i don't know how but the gh pages branch reflecting the same changes 


https://github.com/user-attachments/assets/59cb3f5d-0f91-4324-b7bc-a3e219d04c22

and sir it is also visible on website can you please help me

**Comment by Asymtode712** [comment]
@Ayushmaanagarwal1211 If that's the case then simply you can create 2 PRs one for removing gh-pages content from original `main` branch and another PR for removing main content from original `gh-pages` branch, I think this would normalize the situation

**Comment by Ayushmaanagarwal1211** [comment]
@Asymtode712 alright

**Pull request merged**
