### PR TITLE
Made Changes in the UI of Compare page

### PR DESCRIPTION
**Pull request by HimangshuSharma01**
Before:

https://github.com/user-attachments/assets/37f7ec64-4665-45c1-8d44-003880661456

After:

https://github.com/user-attachments/assets/bc0f0910-11d2-4217-b0a2-835ffd68ede1

ISSUE #878   and   #653

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by HimangshuSharma01** [comment]
@sanjay-kv Sir please add level 3 as this fixes 2 problems of level 2

**Comment by sanjay-kv** [comment]
can u work on to remove the preloader, its looks ugly

**Comment by HimangshuSharma01** [comment]
> can u work on to remove the preloader, its looks ugly

okay sir

**Comment by HimangshuSharma01** [comment]
> can u work on to remove the preloader, its looks ugly

@sanjay-kv sir can we add skeleton loading instead of that?

**Comment by sanjay-kv** [comment]
sample please

**Comment by HimangshuSharma01** [comment]
> sample please

Sir i think the default is better and simple

**Pull request merged**
