### PR TITLE
Redesigning of COC Page

### PR DESCRIPTION
**Pull request by Shariq2003**
https://github.com/user-attachments/assets/fd9a3346-9e87-46f3-a88a-091d9c97591a

#830 completed

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by Shariq2003** [comment]
@sanjay-kv label of level is not showing in my PR

**Comment by Shariq2003** [comment]
Screenshot_2024-10-18-11-39-01-881_com android chrome

Label of level is not showing

**Comment by Shariq2003** [comment]
@sanjay-kv @HimangshuSharma01 sir, please add label of level to this PR.

**Comment by Shariq2003** [comment]
@HimangshuSharma01 sir, thanks alot

**Pull request merged**
