### PR TITLE
Fixed homepage visitor counter to track unique visits only once per user session

### LINKED ISSUE #1195: Feature : Update homepage visitor counter to track unique visitors
Title: Update homepage visitor counter to track unique visitors

**Description:**
Currently, the visitor count increments every time a user navigates back to the homepage, even if they have already been counted. Modify the counter to track unique visitors only, ensuring each user is counted once regardless of how many times they revisit the homepage in the same session. Consider using cookies or local storage to store a flag indicating a user has already been counted.

**Images for reference:**
 - image

@sanjay-kv 
Pls assign me this issue give me level, label.

### PR DESCRIPTION
**Pull request by ygowthamr**
#PR: Fixed homepage visitor counter to track unique visits only once per user session

Fix #1195 

## Description
This PR addresses the issue where the visitor count increments each time a user returns to the homepage, even if they have already been counted. The visitor count now only increments on the first visit per user session, ensuring each visitor is counted only once.

## Changes Made
- Added a check using `localStorage` to track if a user has already visited the homepage.
- If the `visitedHomePage` flag is not set, the visitor count is incremented, and the flag is set in `localStorage`.
- Subsequent visits in the same session do not increment the counter, preserving the unique count.

## Testing
- Verified that the visitor count increments only once per session.
- Tested multiple navigations back to the homepage; count remains stable after the initial increment.

This update ensures accurate visitor tracking by counting each user only once per session.

@sanjay-kv 
Pls assign this, give me labels, level.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@sanjay-kv 
Pls review and merge my PR.

**Review by sanjay-kv — APPROVED** [review]

**Comment by ygowthamr** [comment]
@sanjay-kv 
Please add level and labels.

**Comment by ygowthamr** [comment]
@sanjay-kv 
Pls add level and label, also assign me.

**Comment by sanjay-kv** [comment]
@HimangshuSharma01 remove the counter, its doesnt look good

**Pull request merged**
