### PR TITLE
Feature: Added Reveal elements on scroll

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#213 

### Preview of Feature

https://github.com/user-attachments/assets/3ca2bd25-6994-4993-a1fd-9c936c4e4c01

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Anjaliavv51 can you update your sync fork  and fix these conflicts

**Comment by Anjaliavv51** [comment]
@sanjay-kv sir after try many times still it's showing like this

**Comment by Anjaliavv51** [comment]
> hey @Anjaliavv51 can you update your sync fork and fix these conflicts

@nishant0708 how can i do it?
i am using github desktop
do u have any idea how to do?

**Comment by nishant0708** [comment]
okay see @Anjaliavv51 in your github browser 
image
change main to gh-pages 

After that there you will find option to Sync-fork do that 
then in Vs code go to gh-branch 
image

here in terminal do Git Pull

and now switch to your branch where this code is present and then do

git pull origin gh-pages 

then solve conflicts 
https://www.youtube.com/watch?v=QmKdodJU-js
refer this for solving Conflicts .

then push your code anyway you want it will be fixed

**Comment by Anjaliavv51** [comment]
> okay see @Anjaliavv51 in your github browser image change main to gh-pages
> 
> After that there you will find option to Sync-fork do that then in Vs code go to gh-branch image
> 
> here in terminal do Git Pull
> 
> and now switch to your branch where this code is present and then do
> 
> git pull origin gh-pages
> 
> then solve conflicts https://www.youtube.com/watch?v=QmKdodJU-js refer this for solving Conflicts .
> 
> then push your code anyway you want it will be fixed

@nishant0708  Thank You

**Pull request closed without merging**
