### PR TITLE
Add Github stats page for personalised user experience 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #1072 
Screenshot 2024-10-26 at 1 11 54 AM
@sanjay-kv as you asked me to make it when user logs in then user stats should be visible, for now our login is not working i tried collecting it and saving it to the local storage , but that also was buggy so i implemented it this way for now....

### CODE REVIEW

**Comment by sanjay-kv** [comment]
I think when user login on the page and we make it visible like an dashboard that would be awesome. 
You are great developer and doing out of the box thinking. 

One suggestion would be use badit for the screen recording and put it on PR, as we deal with huge PRs it would make review easy.  @shubhagarwal1

**Comment by sanjay-kv** [comment]
can u help me to fix the conflicts?

**Comment by shubhagarwal1** [comment]
> can u help me to fix the conflicts?

Yes, resolving conflicts now.

**Comment by shubhagarwal1** [comment]
> I think when user login on the page and we make it visible like an dashboard that would be awesome. You are great developer and doing out of the box thinking.
> 
> One suggestion would be use badit for the screen recording and put it on PR, as we deal with huge PRs it would make review easy. @shubhagarwal1

Sir, can i utilise local storage for the usecase

**Comment by sanjay-kv** [comment]
you can use

**Comment by shubhagarwal1** [comment]
> you can use

ok Sir

**Comment by shubhagarwal1** [comment]
> you can use

Working on the issue, i will align this with when user logs in, shoul dabel to see the git stats.

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
