### PR TITLE
ADDED THE TRANSLATOR FUNCTION

### PR DESCRIPTION
**Pull request by HS202022**
ADDED A GOOD TRANSLATOR BUTTON ISSUE #815 

https://github.com/user-attachments/assets/04451317-1bd5-440c-a3fe-dcc218f9a939

### CODE REVIEW

**Comment by HS202022** [comment]
@sanjay-kv Good afternoon sir ,level 2 would be helpful it's working fine .Thank you

**Comment by HS202022** [comment]
@sanjay-kv PLEASE HAVE A LOOK I HAVE FINISHED THE WORK KINDLY GIVE THE LABELS AND LEVEL 2 WOULD BE HELPFUL 
THANK YOU

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
Your contributions are great can you become maintainer of this project, I will sponsor you as well. let me know @HS202022

**Comment by HS202022** [comment]
> Your contributions are great can you become maintainer of this project, I will sponsor you as well. let me know @HS202022 

Sure will there be points for that?

**Comment by sanjay-kv** [comment]
Lets get connected on call. it would be easy. 
let me know if you are free now @HS202022

**Comment by HS202022** [comment]
> Lets get connected on call. it would be easy. 
> let me know if you are free now @HS202022 
Yeah fir sure

**Comment by sanjay-kv** [comment]
https://meet.google.com/ipx-boyw-vtx

@HS202022 join now

**Pull request merged**
