### PR TITLE
visibility fixed in github badge

### LINKED ISSUE #230: Error:  visibility in dark mode
### Describe the Error

In the github badge page, the headings are not visible in dark mode. 

### Expected behavior

The headings and all the text should be clear and visible. 

### Additional context

Screen Shot 2024-08-08 at 4 10 42 PM
Screen Shot 2024-08-08 at 4 10 47 PM
Screen Shot 2024-08-08 at 4 10 52 PM
Screen Shot 2024-08-08 at 4 10 57 PM

@sanjay-kv Please assign it to me under gssoc

### PR DESCRIPTION
**Pull request by hars-21**
Closes #230 

I have changed all the heading color to white in github badges page when in dark mode.

Screen Shot 2024-08-09 at 10 58 21 AM
Screen Shot 2024-08-09 at 10 58 29 AM
Screen Shot 2024-08-09 at 10 58 36 AM

### CODE REVIEW

**Comment by hars-21** [comment]
@sanjay-kv Please see the changes

**Comment by hars-21** [comment]
@sanjay-kv I have resolved the merge conflicts. Please review

**Review by dinxsh — APPROVED** [review]
good job

**Comment by hars-21** [comment]
@dinxsh Thanks!! but can you please assign me and add labels.

**Pull request merged**
